import fs from 'fs';
fs.writeFileSync('components/ProductStructuredData.tsx', Buffer.from('aW1wb3J0IHR5cGUgeyBQcm9kdWN0IH0gZnJvbSAnQC9saWIvdHlwZXMnOwoKY29uc3QgQkFTRSA9ICdodHRwczovL3d3dy5wbGFzdGlsb25hcy5jb20nOwoKLyoqCiAqIEpTT04tTEQgcG9yIHByb2R1Y3RvOiBQcm9kdWN0ICsgQnJlYWRjcnVtYkxpc3QuCiAqCiAqIFJlZ2xhIGRlIGhvbmVzdGlkYWQ6IHNvbG8gZGF0b3MgUkVBTEVTIGRlbCBjYXTDoWxvZ28uIE5PIHNlIGRlY2xhcmFuIHByZWNpb3MsCiAqIHJlc2XDsWFzIG5pIGNhbGlmaWNhY2lvbmVzIChlbCBuZWdvY2lvIGVzIHBvciBjb3RpemFjacOzbikg4oCUIGludmVudGFybG9zIHJvbXBlcsOtYQogKiBlbCByaWNoIHJlc3VsdCBkZSBHb29nbGUgeSBzZXLDrWEgZmFicmljYWNpw7NuLiBMYXMgZXNwZWNpZmljYWNpb25lcyB0w6ljbmljYXMgc8OtCiAqIHNvbiByZWFsZXMgeSBzZSBleHBvbmVuIGNvbW8gYWRkaXRpb25hbFByb3BlcnR5IHBhcmEgZW5yaXF1ZWNlciBlbCBlbnRlbmRpbWllbnRvLgogKi8KZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gUHJvZHVjdFN0cnVjdHVyZWREYXRhKHsgcHJvZHVjdCB9OiB7IHByb2R1Y3Q6IFByb2R1Y3QgfSkgewogIGNvbnN0IHVybCA9IGAke0JBU0V9L3Byb2R1Y3Rvcy8ke3Byb2R1Y3Quc2x1Z31gOwoKICBjb25zdCBwcm9kdWN0TGQgPSB7CiAgICAnQGNvbnRleHQnOiAnaHR0cHM6Ly9zY2hlbWEub3JnJywKICAgICdAdHlwZSc6ICdQcm9kdWN0JywKICAgIG5hbWU6IHByb2R1Y3QubmFtZSwKICAgIGRlc2NyaXB0aW9uOiBwcm9kdWN0LnNob3J0RGVzY3JpcHRpb24sCiAgICBpbWFnZTogYCR7QkFTRX0ke3Byb2R1Y3QuaW1hZ2V9YCwKICAgIGNhdGVnb3J5OiBwcm9kdWN0LmNhdGVnb3J5LAogICAgc2t1OiBwcm9kdWN0LmlkLAogICAgdXJsLAogICAgYnJhbmQ6IHsgJ0B0eXBlJzogJ0JyYW5kJywgbmFtZTogJ1BsYXN0aWxvbmFzIFBlcnVhbmFzIFNBQycgfSwKICAgIG1hbnVmYWN0dXJlcjogewogICAgICAnQHR5cGUnOiAnT3JnYW5pemF0aW9uJywKICAgICAgbmFtZTogJ1BsYXN0aWxvbmFzIFBlcnVhbmFzIFNBQycsCiAgICAgICdAaWQnOiBgJHtCQVNFfS8jYnVzaW5lc3NgLAogICAgfSwKICAgIC4uLihwcm9kdWN0LnNwZWNpZmljYXRpb25zPy5sZW5ndGgKICAgICAgPyB7CiAgICAgICAgICBhZGRpdGlvbmFsUHJvcGVydHk6IHByb2R1Y3Quc3BlY2lmaWNhdGlvbnMubWFwKChzKSA9PiAoewogICAgICAgICAgICAnQHR5cGUnOiAnUHJvcGVydHlWYWx1ZScsCiAgICAgICAgICAgIG5hbWU6IHMubGFiZWwsCiAgICAgICAgICAgIHZhbHVlOiBzLnZhbHVlLAogICAgICAgICAgfSkpLAogICAgICAgIH0KICAgICAgOiB7fSksCiAgfTsKCiAgY29uc3QgYnJlYWRjcnVtYkxkID0gewogICAgJ0Bjb250ZXh0JzogJ2h0dHBzOi8vc2NoZW1hLm9yZycsCiAgICAnQHR5cGUnOiAnQnJlYWRjcnVtYkxpc3QnLAogICAgaXRlbUxpc3RFbGVtZW50OiBbCiAgICAgIHsgJ0B0eXBlJzogJ0xpc3RJdGVtJywgcG9zaXRpb246IDEsIG5hbWU6ICdJbmljaW8nLCBpdGVtOiBCQVNFIH0sCiAgICAgIHsgJ0B0eXBlJzogJ0xpc3RJdGVtJywgcG9zaXRpb246IDIsIG5hbWU6ICdQcm9kdWN0b3MnLCBpdGVtOiBgJHtCQVNFfS9wcm9kdWN0b3NgIH0sCiAgICAgIHsgJ0B0eXBlJzogJ0xpc3RJdGVtJywgcG9zaXRpb246IDMsIG5hbWU6IHByb2R1Y3QubmFtZSwgaXRlbTogdXJsIH0sCiAgICBdLAogIH07CgogIHJldHVybiAoCiAgICA8PgogICAgICA8c2NyaXB0IHR5cGU9ImFwcGxpY2F0aW9uL2xkK2pzb24iIGRhbmdlcm91c2x5U2V0SW5uZXJIVE1MPXt7IF9faHRtbDogSlNPTi5zdHJpbmdpZnkocHJvZHVjdExkKSB9fSAvPgogICAgICA8c2NyaXB0IHR5cGU9ImFwcGxpY2F0aW9uL2xkK2pzb24iIGRhbmdlcm91c2x5U2V0SW5uZXJIVE1MPXt7IF9faHRtbDogSlNPTi5zdHJpbmdpZnkoYnJlYWRjcnVtYkxkKSB9fSAvPgogICAgPC8+CiAgKTsKfQo=','base64').toString('utf8'));
console.log('  escrito components/ProductStructuredData.tsx');
let s = fs.readFileSync('app/productos/[slug]/page.tsx','utf8');
if (!s.includes('ProductStructuredData')) {
  s = s.replace("import ProductAvailability from '@/components/ProductAvailability';",
    "import ProductAvailability from '@/components/ProductAvailability';\nimport ProductStructuredData from '@/components/ProductStructuredData';");
  const oldMeta = "  return {\n    title: product.name,\n    description: product.shortDescription,\n  };";
  const newMeta = "  const canonical = `/productos/${product.slug}`;\n  const ogTitle = `${product.name} — Plastilonas Peruanas SAC`;\n  return {\n    title: product.name,\n    description: product.shortDescription,\n    keywords: [product.name, product.category, ...product.sector, 'Perú', 'proveedor', 'fabricante'],\n    alternates: { canonical },\n    openGraph: { title: ogTitle, description: product.shortDescription, url: canonical, type: 'website' },\n    twitter: { card: 'summary_large_image', title: ogTitle, description: product.shortDescription },\n  };";
  if (!s.includes(oldMeta)) throw new Error('bloque metadata no encontrado');
  s = s.replace(oldMeta, newMeta);
  s = s.replace('    <div className="max-w-6xl mx-auto px-6 py-10">\n',
    '    <div className="max-w-6xl mx-auto px-6 py-10">\n      <ProductStructuredData product={product} />\n');
  fs.writeFileSync('app/productos/[slug]/page.tsx', s);
  console.log('  parcheado app/productos/[slug]/page.tsx');
} else console.log('  page ya tenía schema — omitido');
console.log('LISTO: SEO de producto (Product + BreadcrumbList + OG/canonical)');
